#!/bin/sh

# mon (C) R.E.Wolff@BitWizard.nl
#
# script to show the changes in the first 16 bytes of a DMX universe
# in a terminal window. 
# 2026-03-04 : Modified to work with the two HD commands I have here. --REW

interval=.1
while true ; do 
  hd dmxdata | grep '^0* '
  sleep $interval
done

